services:
  - type: web
    name: greencart-api
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings.production
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: greencart-db
          property: connectionString
      - key: PORT
        value: "8000"
      - key: WORKERS
        value: "3"
      - key: POPULATE_TEST_DATA
        value: "true"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1,greencart-api.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://*.onrender.com,https://greencart-api.onrender.com,http://localhost:3000,http://127.0.0.1:3000"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com,https://greencart-api.onrender.com"

databases:
  - name: greencart-db
    plan: free
    databaseName: greencart
    user: greencart_user